name: CI
env:
  EB_PACKEGE_S3_BUCKET_NAME: "20-cicd-packages-us"
  EB_APLICATION_NAME: "20CICD"
  EB_ENVIRONMENT_NAME: "20cicd-env-1"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-1"

on:

  push:
    branches:
      - 20_CICD

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Pyhton
        uses: actions/setup-python@v3
        with:
          python-verion: '3.9.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake pytest

      -name: Lint with flake8 without docker-compose
        run: |
          flake8 app --count --select=E9,F63,F7,F82,W391 --show-source --statistics
          flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        - name: Run pytests
          run: pytest tests

        - name: Print Happy Message
          run: echo "Pytests part finished successfully"
  build:
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v3

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy Deployment package to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }}  s3://${{env.EB_PACKEGE_S3_BUCKET_NAME }}/

      - name: Print Happy Message for CI finish
        run: echo "Ci part finishe successfully"


  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Create new ElasticBeanstalk Application
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKEGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Ver-${{ github.sha }}"

      - name: Print Happy Message for CD finish
        run: echo "CD part finishe successfully"
            
         
 
